-- =============================================================================
-- Agronavis: Complete Database Schema — Run this in Supabase SQL Editor
-- =============================================================================
-- Order of operations:
--   1. Create all tables (farmers, farms, crops, sensor_readings, advisories)
--   2. Create indexes for common query patterns
--   3. Create the trigger that auto-populates farmers from auth.users
--   4. Enable RLS and define row-level security policies
-- =============================================================================


-- ─── 1. TABLES ───────────────────────────────────────────────────────────────

-- Farmer profile — one row per authenticated user
CREATE TABLE IF NOT EXISTS public.farmers (
  id            uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email         text NOT NULL,
  full_name     text NOT NULL DEFAULT 'Farmer',
  phone         text,
  language      text NOT NULL DEFAULT 'en',
  state         text,
  district      text,
  avatar_url    text,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now()
);

-- Farm — a farmer can own multiple farm plots
CREATE TABLE IF NOT EXISTS public.farms (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  farmer_id     uuid NOT NULL REFERENCES public.farmers(id) ON DELETE CASCADE,
  name          text NOT NULL,
  area_acres    numeric(8, 2),
  soil_type     text,
  irrigation    text,
  latitude      numeric(10, 7),
  longitude     numeric(10, 7),
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now()
);

-- Crop — each planting season on a farm
CREATE TABLE IF NOT EXISTS public.crops (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  farm_id       uuid NOT NULL REFERENCES public.farms(id) ON DELETE CASCADE,
  farmer_id     uuid NOT NULL REFERENCES public.farmers(id) ON DELETE CASCADE,
  name          text NOT NULL,
  variety       text,
  category      text,
  sown_date     date,
  harvest_date  date,
  status        text NOT NULL DEFAULT 'active'
                CHECK (status IN ('active', 'harvested', 'failed')),
  created_at    timestamptz NOT NULL DEFAULT now()
);

-- Sensor readings — IoT data points tied to a farm
CREATE TABLE IF NOT EXISTS public.sensor_readings (
  id            bigserial PRIMARY KEY,
  farm_id       uuid NOT NULL REFERENCES public.farms(id) ON DELETE CASCADE,
  sensor_type   text NOT NULL,   -- e.g. 'soil_moisture', 'temperature', 'humidity'
  value         numeric(10, 4) NOT NULL,
  unit          text NOT NULL,
  recorded_at   timestamptz NOT NULL DEFAULT now()
);

-- AI advisories — recommendations generated by the ML model
CREATE TABLE IF NOT EXISTS public.advisories (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  farmer_id     uuid NOT NULL REFERENCES public.farmers(id) ON DELETE CASCADE,
  farm_id       uuid REFERENCES public.farms(id) ON DELETE SET NULL,
  crop_id       uuid REFERENCES public.crops(id) ON DELETE SET NULL,
  category      text NOT NULL,   -- e.g. 'irrigation', 'fertilizer', 'pest', 'weather'
  title         text NOT NULL,
  body          text NOT NULL,
  severity      text NOT NULL DEFAULT 'info'
                CHECK (severity IN ('info', 'warning', 'critical')),
  source        text NOT NULL DEFAULT 'ml_model',
  read          boolean NOT NULL DEFAULT false,
  created_at    timestamptz NOT NULL DEFAULT now()
);


-- ─── 2. INDEXES ──────────────────────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_farms_farmer_id        ON public.farms(farmer_id);
CREATE INDEX IF NOT EXISTS idx_crops_farm_id          ON public.crops(farm_id);
CREATE INDEX IF NOT EXISTS idx_crops_farmer_id        ON public.crops(farmer_id);
CREATE INDEX IF NOT EXISTS idx_sensor_farm_recorded   ON public.sensor_readings(farm_id, recorded_at DESC);
CREATE INDEX IF NOT EXISTS idx_advisories_farmer_id   ON public.advisories(farmer_id, created_at DESC);


-- ─── 3. TRIGGER: auto-create farmer profile on signup ────────────────────────

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.farmers (id, email, full_name, created_at)
  VALUES (
    new.id,
    new.email,
    COALESCE(new.raw_user_meta_data->>'full_name', 'Farmer'),
    new.created_at
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN new;
EXCEPTION
  WHEN OTHERS THEN
    -- Log but never block authentication
    RAISE WARNING 'handle_new_user failed for user %: %', new.id, SQLERRM;
    RETURN new;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- Auto-update updated_at on farmers and farms
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  new.updated_at = now();
  RETURN new;
END;
$$;

DROP TRIGGER IF EXISTS trg_farmers_updated_at ON public.farmers;
CREATE TRIGGER trg_farmers_updated_at
  BEFORE UPDATE ON public.farmers
  FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

DROP TRIGGER IF EXISTS trg_farms_updated_at ON public.farms;
CREATE TRIGGER trg_farms_updated_at
  BEFORE UPDATE ON public.farms
  FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();


-- ─── 4. ROW LEVEL SECURITY ───────────────────────────────────────────────────

ALTER TABLE public.farmers         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.farms           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.crops           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sensor_readings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.advisories      ENABLE ROW LEVEL SECURITY;

-- farmers
DROP POLICY IF EXISTS "farmers_select_own" ON public.farmers;
CREATE POLICY "farmers_select_own"
  ON public.farmers FOR SELECT USING (auth.uid() = id);

DROP POLICY IF EXISTS "farmers_update_own" ON public.farmers;
CREATE POLICY "farmers_update_own"
  ON public.farmers FOR UPDATE USING (auth.uid() = id);

-- farms (farmer owns all their farms)
DROP POLICY IF EXISTS "farms_select_own" ON public.farms;
CREATE POLICY "farms_select_own"
  ON public.farms FOR SELECT USING (auth.uid() = farmer_id);

DROP POLICY IF EXISTS "farms_insert_own" ON public.farms;
CREATE POLICY "farms_insert_own"
  ON public.farms FOR INSERT WITH CHECK (auth.uid() = farmer_id);

DROP POLICY IF EXISTS "farms_update_own" ON public.farms;
CREATE POLICY "farms_update_own"
  ON public.farms FOR UPDATE USING (auth.uid() = farmer_id);

DROP POLICY IF EXISTS "farms_delete_own" ON public.farms;
CREATE POLICY "farms_delete_own"
  ON public.farms FOR DELETE USING (auth.uid() = farmer_id);

-- crops
DROP POLICY IF EXISTS "crops_select_own" ON public.crops;
CREATE POLICY "crops_select_own"
  ON public.crops FOR SELECT USING (auth.uid() = farmer_id);

DROP POLICY IF EXISTS "crops_insert_own" ON public.crops;
CREATE POLICY "crops_insert_own"
  ON public.crops FOR INSERT WITH CHECK (auth.uid() = farmer_id);

DROP POLICY IF EXISTS "crops_update_own" ON public.crops;
CREATE POLICY "crops_update_own"
  ON public.crops FOR UPDATE USING (auth.uid() = farmer_id);

DROP POLICY IF EXISTS "crops_delete_own" ON public.crops;
CREATE POLICY "crops_delete_own"
  ON public.crops FOR DELETE USING (auth.uid() = farmer_id);

-- sensor_readings (readable if the farmer owns the farm)
DROP POLICY IF EXISTS "sensor_select_own_farm" ON public.sensor_readings;
CREATE POLICY "sensor_select_own_farm"
  ON public.sensor_readings FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.farms
      WHERE farms.id = sensor_readings.farm_id
        AND farms.farmer_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "sensor_insert_own_farm" ON public.sensor_readings;
CREATE POLICY "sensor_insert_own_farm"
  ON public.sensor_readings FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.farms
      WHERE farms.id = sensor_readings.farm_id
        AND farms.farmer_id = auth.uid()
    )
  );

-- advisories
DROP POLICY IF EXISTS "advisories_select_own" ON public.advisories;
CREATE POLICY "advisories_select_own"
  ON public.advisories FOR SELECT USING (auth.uid() = farmer_id);

DROP POLICY IF EXISTS "advisories_update_own" ON public.advisories;
CREATE POLICY "advisories_update_own"
  ON public.advisories FOR UPDATE USING (auth.uid() = farmer_id);
